language: node_js
node_js:
  - "4.7"
  - "5.12"
  - "6.9"
  - "7.4"
notifications:
  slack:
    on_success: never
    on_failure: always
sudo: false
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    tags: true
