language: node_js
node_js:
  - "6.17"
  - "8.16"
  - "10.15"
  - "12.2"
notifications:
  slack:
    on_success: never
    on_failure: always
sudo: false
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    tags: true
